#pragma once
#define WINDOW_HEIGHT 600
#define WINDOW_WIDTH 1000

#define SCORE_POS_WIDTH 20
#define SCORE_POS_HEIGHT 20 
#define FONT_SIZE 18

#define BUTTON_START_POS_Y 200.0f
#define BUTTON_WIDTH 360.0f
#define BUTTON_HEIGHT 60.0f

#define SCORE_TEXT_START_POST_Y 150.0f

#define JUMP_DELAY 0

#define V_START 0.88f
#define ACCELERATION 0.169f

#define GROUND_HEIGHT 145

#define PLAYER_WIDTH 40
#define PLAYER_HEIGHT 50
#define PLAYER_START_POS_X 40
#define PLAYER_START_POS_Y (WINDOW_HEIGHT - GROUND_HEIGHT - PLAYER_HEIGHT)

#define CACT_SMALL_WIDTH 35
#define CACT_BIG_WIDTH 50
#define CACT_HEIGHT 60
#define CACT_START_POS_X (WINDOW_WIDTH - 60)
#define CACT_START_POS_Y (WINDOW_HEIGHT - GROUND_HEIGHT - CACT_HEIGHT + 10)
#define CACTUS_VELOCITY 3
#define CACTUS_SWITCH_TIME 0.008f

#define FLYING_DINOSAUR_HEIGHT 70
#define FLYING_DINOSAUR_WIDTH 120
#define FLYING_DINOSAUR_VELOCITY 3
#define FLYING_DINOSAUR_SWITCH_TIME 0.008f
#define FLYING_DINOSAUR_START_POS_X (WINDOW_WIDTH - 60)
#define FLYING_DINOSAUR_START_POS_Y 108
#define FLYING_DINOSAUR_TEXTURE_SWITCH_TIME 0.8f

#define COIN_WIDTH 50
#define COIN_HEIGHT 50
#define COIN_VELOCITY 2
#define COIN_SWITCH_TIME 0.008f
#define COIN_START_POS_X (WINDOW_WIDTH - 60)
#define COIN_START_POS_Y 240

#define GAME_POINTS_SWITCH_TIME 0.1f
#define GAME_POINTS_PER_TIME_UNIT 1

#define SPAWNING_TIME_COIN 10.0f
#define SPAWNING_TIME_FLYING_DINOSAUR 7.0f
#define SPAWNING_TIME_CACTUS 1.5f

#define ALFA 60

#define MENU_SPACING 20.0f